### ISSUE TITLE
Make use of patched folder consistent

### ISSUE THREAD

**Issue by plopesc** [Roomify/RoomifyAgency#4]
I checked project .make file and you've a bunch of patched modules.

One of them - plupload - is being installed in "patched" folder, however the rest of them, like field_collection are placed in "contrib" folder.

I believe you would be a good idea make this consistent, moving plupload to contrib or all the other patched modules to patched folder.

What do you think?

**Comment by istos** [comment]
Hi Pablo - the convention we are using is that plupload is actually directly patched by us and not by pulling patches from d.o. - for any other modules that are patched the info is in the make file.

**Comment by plopesc** [comment]
Understood. Closing then.
Thanks @istos
